apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: splunk-dev
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: github-platform
  path: ./clusters/dev/splunk
  prune: true
  wait: true
  timeout: 10m
